packages:
  - apps/*
  - packages/*
  - video

ignoredBuiltDependencies:
  - esbuild
  - koffi
  - protobufjs
  - sharp

onlyBuiltDependencies:
  - electron

patchedDependencies:
  '@mariozechner/pi-ai@0.60.0': patches/@mariozechner__pi-ai@0.60.0.patch
